version: '2'

services:
   database:
     image: mysql
     volumes:
       - /home/sql_data_docker:/var/lib/mysql
     environment:
       - MYSQL_ROOT_PASSWORD=password
       - MYSQL_USER=root
       - MYSQL_PASSWORD=password
     expose:
       - "3306"

   api:
     build: homeautomationapi
     depends_on:
       - database
     expose:
       - "8080"
     ports:
       - "8080:8080"
     volumes:
       - /usr/src/app
     environment:
       - MYSQL_USER=root
       - MYSQL_PASSWORD=password

   web:
     build: homeautomationgui
     depends_on:
       - api
     ports:
       - "80:80"
